split_seed: 0
val_size: 0.2
test_size: 0.2

data_dir: data
spectrogram_dir: uleec
labels_file: ulabels.csv

sr: 22050

spectrogram_config:
    n_fft: 2048
    hop_length: 256
    win_length: 2048
    window: hamming
    center: False
    pad_mode: null
    power: 1.0
    n_mels: 256
    fmin: 10
    fmax: 11025
    htk: False
    norm: null

lower_threshold: -25
upper_threshold: 35

class_order: ["day", "night"]
class_order_2: ["day", "night"]

extension: png

precision: 16

segment_length: 3
split_shape: 253

seed: 0

batch_size: 128

model_name: vit_base
initialization: google/vit-base-patch16-224-in21k
convert_tf_params: true
num_classes: 12
trainable_weights: all
always_mutable_bn: false
