model_name: resnet_50
initialization: imagenet
always_mutable_bn: false

batch_size: 256

log_learning_rate: -1.5020174980163574
log_weight_decay: -0.6475253105163574
sub_log_momentum: -2.678025960922241

mixup_alpha: 2.0
cutmix_alpha: 0.2

hpsearch_ranges:
    training_seed: {0, 1, 2, 3, 4}

hpsearch_seed: 0
hpsearch_iterations: 5
hpsearch_function: grid

evaluate_on_test: false
