_target_: soundscape.log.Logger

logged_keys:
  - epoch
  - ce_loss
  - bal_acc
  - bal_acc_w
  - brier
  - logits
  - labels
  - ids

pbar_keys:
  - epoch
  - ce_loss
  - val_ce_loss
  - bal_acc
  - val_bal_acc
  - val_bal_acc_w

merge_fn: concat