_target_: soundscape.log.WandbLogger

saved_keys:
  - train_logits
  - val_logits
  - test_logits
  - train_labels
  - val_labels
  - test_labels
  - train_ids
  - val_ids
  - test_ids

merge_fn: stack

nan_metrics:
  - train_ce_loss
  - val_ce_loss
  - test_ce_loss

optimizing_metric: val_bal_acc
patience: 5

wandb_settings:
  project: soundscape