split_seed: 0
val_size: 0.2
test_size: 0.2

data_dir: data
spectrogram_dir: leec
labels_file: labels.csv

sr: 22050

spectrogram_config:
    n_fft: 2048
    hop_length: 256
    win_length: 2048
    window: hamming
    center: False
    pad_mode: null
    power: 1.0
    n_mels: 256
    fmin: 10
    fmax: 11025
    htk: False
    norm: null

lower_threshold: -25
upper_threshold: 35

precision: 16

segment_length: 5
pad_mode: reflect