data_dir: data
spectrogram_dir: leec

precision: 16

segment_length: 5
cropped_length: 3

class_order: [ "other", "basi_culi", "myio_leuc", "vire_chiv", "cycl_guja", "pita_sulp", "zono_cape", "dend_minu", "apla_leuc", "isch_guen", "phys_cuvi", "boan_albo", "aden_marm"]
class_order_2: ["bird", "frog"]

num_classes: 12

extension: png

channel_mean: [0.485, 0.456, 0.406]
channel_std: [0.229, 0.224, 0.225]
