seed: 1

data:
  data_dir: data
  num_classes: 12   # 2, 12 or 13
  downsample: true

  spectrogram:
    window_size: 2048
    hop_size: 256
    n_fft: 2048
    window_fn: hamming_window
    n_mels: 256

  fragmentation:
    fragment_size: 5
    padding_mode: edge
    begin_time_fn: uniform
    min_overlap: 0.5

  split:
    val_frac: 0.2
    test_frac: 0.2

model:
  name: resnet_18

train:
  num_epochs: 100
  batch_size: 32
  balanced: false
  learning_rate: 0.05
  partition_fn: all
  optimizing_metric: balanced_accuracy

