defaults:
  - dataloader: leec12
  - model: resnet50
  - optimizer: adamw
  - augmentation: leec
  - logger: logger
  - logger@epoch_logger: epoch_logger

seed: 0
num_epochs: 100

optimizer:
  epochs: 100

dataloader:
  batch_size: 2