FROM nvcr.io/nvidia/jax:23.10-paxml-py3

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y 
RUN apt-get install -y software-properties-common build-essential libblas-dev libhdf5-serial-dev unzip
RUN apt-get install -y git tmux htop zsh neovim curl
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN git config --global --add safe.directory /home/jmsilva/soundscape
RUN git config --global user.email joaomarcoscsilva@usp.br
RUN git config --global user.name "João Marcos Cardoso da Silva"

RUN python -m pip install -U pip
RUN pip install transformers p_tqdm hydra-core dm-haiku jax_resnet imageio librosa kaggle 
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install wandb

WORKDIR /root
CMD zsh
