
# Data preprocessing settings
# ===

split_seed: 0
val_size: 0.2
test_size: 0.2

data_dir: data
spectrogram_dir: leec
labels_file: labels.csv

sr: 22050

spectrogram_config:
    n_fft: 2048
    hop_length: 256
    win_length: 2048
    window: hamming
    center: False
    pad_mode: null
    power: 1.0
    n_mels: 256
    fmin: 10
    fmax: 11025
    htk: False
    norm: null

lower_threshold: -25
upper_threshold: 35

class_order: [ "other", "basi_culi", "myio_leuc", "vire_chiv", "cycl_guja", "pita_sulp", "zono_cape", "dend_minu", "apla_leuc", "isch_guen", "phys_cuvi", "boan_albo", "aden_marm"]
class_order_2: ["bird", "frog"]

extension: png

precision: 16

segment_length: 5

# ===
# Model training settings
# ===


cropped_length: 3
pad_mode: reflect

num_classes: 12

optim_name: sgd
model_name: resnet_50
initialization: imagenet
trainable_weights: all
epochs: 128
always_mutable_bn: false

crop_type: deterministic
cutout_alpha: null
mixup_alpha: null
cutmix_alpha: null

batch_size: 128

save_weights: true
early_stopping: false
optimizing_metric: mean_val_bal_acc_nb
optimizing_mode: max
give_up_after: 15
give_up_threshold: 0.1

save_log: true

log_learning_rate: -0.38142103
log_weight_decay: -0.3489557
sub_log_momentum: -0.6722374
mixup_alpha: 1.0077623
cutmix_alpha: 0.34845614

training_seed: 0

# hpsearch_ranges:
#     mixup_alpha: [0.3, 1.0]
#     cutmix_alpha: [-0.1, 0.4]

# hpsearch_iterations: 6
# hpsearch_function: random
# hpsearch_seed: 1
# hpsearch_begin: 0
# hpsearch_indices: {}

evaluate_on_test: true


ensemble_labels_file: data/resnetb_ens_labels.pkl
split_shape: 253