_target_: soundscape.dataset.dataset.Dataset
dataset_dir: data/leec
source_dir: data
data_type: image
sample_length: 5
sr: 22050

splitting:
  split_seed: 0
  splits: ["train", "val", "test"]
  fractions: [0.6, 0.2, 0.2]
  stratify: true

preprocessing:
  raw_dataset_dir: data/wavs
  labels_file: data/labels.csv

  pad_mode: reflect

  spectrogram_kwargs:
    n_fft: 2048
    hop_length: 256
    win_length: 2048
    window: hamming
    center: False
    pad_mode: null
    power: 1.0
    n_mels: 256
    fmin: 10
    fmax: 11025
    htk: False
    norm: null

  thresholds: [-25, 35]
  image_precision: 16
