defaults:
  - reading_function: read_image

_target_: dataset.Dataset

dataset_dir: data/leec

class_names: [ "basi_culi", "myio_leuc", "vire_chiv", "cycl_guja", "pita_sulp", "zono_cape", "dend_minu", "apla_leuc", "isch_guen", "phys_cuvi", "boan_albo", "aden_marm"]
class_to_id: null